POST http://localhost:3000/signup
Content-Type: application/json

{
    "fullname": "Shegayenesh Seyfu",
    "username": "seble",
    "email": "sebleseyfuss@gmail.com",
    "password": "123456",
    "confirmpassword": "sebless1234"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "sebli",
    "password": "sebless1234"
}

###

GET http://localhost:3000/Login

###
GET http://localhost:3000/home

###

POST http://localhost:3000/addContact
Content-Type: application/json

{
    "fullName": "Abel",
    "phoneNumber": "1234567890",
    "email": "codshf@gmaij.com",
    "notes": "wohoo"
}

###
DELETE  http://localhost:3000/delete/674d6bd38975e90b077aba9c
### 
GET http://localhost:3000/contacts

###

POST http://localhost:3000/contact/search
Content-Type: application/json

{
    "name": "Abel Tesfa"
}

###
POST http://localhost:3000/logout

###
DELETE http://localhost:3000/delete/users/6747540440c8bc1e52acae64

###
POST http://localhost:3000/user/password
Content-Type: application/json

{
    "username": "abelaaa",
    "currentPassword": "111111",
    "newPassword": "222222"
}

###
POST http://localhost:3000/api/chat
Content-Type: application/json
{
    "message": "how can i use a contact management system"
}

###
Delete http://localhost:3000/delete/67586f33f8ee44078a361d7b