POST http://localhost:3000/signup
Content-Type: application/json

{
    "fullname": "Abel Tesfa",
    "username": "abbebe",
    "password": "123456",
    "confirmpassword": "123456"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "abelat",
    "password": "123456"
}

###

GET http://localhost:3000/Login

###
GET http://localhost:3000/home

###

POST http://localhost:3000/addContact
Content-Type: application/json

{
    "fullName": "Abel Tesfa",
    "phoneNumber": "1234567890",
    "email": "codshf@gmaij.com",
    "notes": "wohoo"
}

###
DELETE  http://localhost:3000/delete/67342cc3eddc86d154995678

### 
GET http://localhost:3000/contacts

###

POST http://localhost:3000/contact/search
Content-Type: application/json

{
    "name": "Abel Tesfa Awel"
}